### ISSUE TITLE
[Bug] Comments on data requests are duplicated on page refresh

### ISSUE THREAD

**Issue by andela-dhaniabelega** [CodeForAfricaLabs/ckanext-datarequests#10]
### Ckan version
2.6.3

### Bug Summary
When a user comments on a data request and refreshes the browser, the new comment is duplicated and continues to duplicate every time the page is refreshed as long the user does not leave the comments page.

### How to reproduce
This bug can be reproduced by commenting on any data request and refreshing the browser. Your comment will be duplicated as long as you do not leave the comments page.

**Comment by NaiRobley** [comment]
@shemogumbe I can work on this

**Comment by NaiRobley** [comment]
As I tried to figure out the origin of this bug I found out that:
If you submitted a form, performing a POST and then hit refresh, the browser will do another POST with the same.

This is the reason the comments are being duplicated upon refresh.

My first thought was to redirect to the same URL of the current comments page but this leads to a loop of redirects since it is the same endpoint that is responsible for GET and POST requests.

My proposed solution is to add a new different end-point for creating new comments on the backend.

I need feedback regarding the origin of the bug and my proposed solution and also any other ideas that may help solve the bug.

**Comment by andela-onnenanya** [comment]
@NaiRobley Add this code to `ckanext.datarequests.controllers.ui_controller` (line `371` in my own code).
`base.redirect(helpers.url_for(controller='ckanext.datarequests.controllers.ui_controller:DataRequestsUI', action='comment', id=id))`

This snapshot may help you see where to add the code in case you have added some code in your own code.

![image](https://user-images.githubusercontent.com/26964897/30598915-f31b8eca-9d52-11e7-8cbc-60cc3c00d085.png)


This fixes the error without having to create a new endpoint.

**Comment by andela-dhaniabelega** [comment]
haha Obinna, I Was just typing the same solution before your comment came in.

**Comment by andela-onnenanya** [comment]
Ok, cool!

**Comment by NaiRobley** [comment]
I tried redirecting earlier and it didn't work but can't remember how I did it. I will try your method and get back to you. Thanks

**Comment by NaiRobley** [comment]
Thanks @andela-onnenanya and @andela-dhaniabelega. Your solution works
